/* eslint-disable no-undef */
const { Sequelize } = require('sequelize');
const User = require('../../entity/User');
const UserModel = require('../../model/userModel');
const UserRepository = require('../userRepository');
const UserIdNotDefinedError = require('../error/userIdNotDefinedError');

const sequelizeInstance = new Sequelize('sqlite::memory');

/**
 * @type UserRepository
 */
let repository;

const sampleUser = new User({
  firstName: 'Juan Maria',
  lastName: 'Fernandez',
  documentType: 'DNI',
  documentNumber: 41072694,
  nationality: 'Argentina',
  address: 'Av. San Martin 270',
  phoneNumber: '3329655848',
  email: 'example@example.com',
  birthdate: '17/4/1998',
});

beforeAll(() => {
  const user = UserModel.setup(sequelizeInstance);
  repository = new UserRepository(user);
});

beforeEach(async () => {
  await sequelizeInstance.sync({ force: true });
});

test('Crea un usuario cuando la entidad no tiene id', async () => {
  const NEW_AUTOGENERATED_ID = 1;
  const newUser = await repository.save(sampleUser);
  expect(newUser.id).toEqual(NEW_AUTOGENERATED_ID);
});

test('Llamar a getById con un  id correcto devuelve un usuario especifico', async () => {
  const NEW_AUTOGENERATED_ID = 1;
  const newUser = await repository.save(sampleUser);
  const exampleUser = await repository.getById(NEW_AUTOGENERATED_ID);
  expect(exampleUser).toEqual(newUser);
});

test('Llamar a getById  sin parametros devuelve un error especifico', () => {
  expect(repository.getById()).rejects.toThrowError(UserIdNotDefinedError);
});
